spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
